export const CONSTANT = Object.freeze({
  EMAIL: "Email",
  DASHBOARD: "Dashboard",
  SUBMIT: "Submit",
  SUCCESS: "Success",
  ERROR: "Error",
  SWW: "Something went wronge.",
  SIGNOUT: "Sign Out",
  LOGIN: "Login",
  SIGNUP: "Sign Up",
  SIGNIN: "Sign In",
  USERNAME: "Username",
  PASSWORD: "Password",
  CONFIRMPASSWORD: "Confirm Password",
  FIRSTNAME: "First Name",
  LASTNAME: "Last Name",
  PHONENUMBER: "Phone Number",
  EMAILADDRESS: "Email Address",
  FORGOTPASSWORD: "Forgot Password",
  TERMS: "Terms of service",
  PRIVACY: "Privacy policy",
  GETSTARTED: "Get Started",
  CREATE_ACC: "Create account",
  PAST_TAX_FILE: "Past Tax Filings",
  OVERVIEW: "Overview",
  SEEALL: "See All",
  PERSONAL_TAX: "Personal Taxs",
  LIMITED_COMPANY: "Limited Company",
  PARTNERSHIP_TAX: "Partnership Tax",
  INSIGHTS_GUIDES: "Insights & Guides",
  SETTINGS: "Settings",
  BUSINESSES: "Businesses",
  ACCOUNTANTS: "Accountants",
  CUSTOMERS: "Customers",
  ASSESSMENT_STATUS: "Assessments Status",
  REPORTS: "Reports",
  CLIENTS: "Clients",
  INSIGHTS_AND_DUIDES: "Insights & Guides",
  IMPORTANT_DATES: "Important Dates",
  TAX_FILLING: "Tax Filings",
  CHAT_HISTORY: "Chat History",
});
export const ROUTES = Object.freeze({
  DASHBOARD: "/dashboard",
  LOGIN: "/login",
  SIGNUP: "/signup",
  USER_PROFILE: "/profile",

  // Admin Routes
  ADMIN_DASHBOARD: "/admin/dashboard",
  SUPER_ADMIN_DASHBOARD: "/super-admin/dashboard",

});
export const ERROR_MESSAGE = Object.freeze({
  INVALID_EMAIL: "Invalid email",
  INVALID_PASSWORD: "Password cannot be empty",
  MISMATCHED_PASSWORD: "Passwords did not match",
});
export const USER_TYPE = Object.freeze({
  CUSTOMER: "customer",
  ADMIN: "admin",
  SUPER_ADMIN: "super_admin",
});
