export const CONSTANT = Object.freeze({
  EMAIL: "Email",
  DASHBOARD: "Dashboard",
  SUBMIT: "Submit",
  SUCCESS: "Success",
  ERROR: "Error",
  SWW: "Something went wronge.",
  SIGNOUT: "Sign Out",
  LOGIN: "Login",
  SIGNUP: "Sign Up",
  SIGNIN: "Sign In",
  USERNAME: "Username",
  PASSWORD: "Password",
  CONFIRMPASSWORD: "Confirm Password",
  FIRSTNAME: "First Name",
  LASTNAME: "Last Name",
  PHONENUMBER: "Phone Number",
  EMAILADDRESS: "Email Address",
  FORGOTPASSWORD: "Forgot Password",
  TERMS: "Terms of service",
  PRIVACY: "Privacy policy",
  GETSTARTED: "Get Started",
  CREATE_ACC: "Create account",
  PAST_TAX_FILE: "Past Tax Filings",
  OVERVIEW: "Overview",
  SEEALL: "See All",
  PERSONAL_TAX: "Personal Taxs",
  LIMITED_COMPANY: "Limited Company",
  PARTNERSHIP_TAX: "Partnership Tax",
  INSIGHTS_GUIDES: "Insights & Guides",
  SETTINGS: "Settings",
  BUSINESSES: "Businesses",
  ACCOUNTANTS: "Accountants",
  CUSTOMERS: "Customers",
  ASSESSMENT_STATUS: "Assessments Status",
  REPORTS: "Reports",
  CLIENTS: "Clients",
  INSIGHTS_AND_DUIDES: "Insights & Guides",
  IMPORTANT_DATES: "Important Dates",
  TAX_FILLING: "Tax Filings",
  CHAT_HISTORY: "Chat History",
});
export const ROUTES = Object.freeze({
  // Customer Routes

  DASHBOARD: "/dashboard",
  LOGIN: "/login",
  SIGNUP: "/signup",
  ASSESSMENT: "/assessment",
  OVERVIEW: "/overview",
  PROFILE: "/profile",
  SETTINGS: "/settings",
  CUSTOMERP_ROFILE: "/customerprofile",
  PERSONAL_TAX: "/personaltax",
  PARTNERSHIP_TAX: "/partnershiptax",
  INSIGHTS_GUIDES: "/insights-guides",
  LIMITED_COMPANY: "/limited-company",
  BUSINESSES: "/businesses",
  ACCOUNTANTS: "/accountants",
  CUSTOMERS: "/customers",

  // Admin Routes

  ADMIN_BUSINESSES: "/admin/businesses",
  ADMIN_ACCOUNTANTS: "/admin/accountants",
  ADMIN_CLIENTS: "/admin/clients",
  ADMIN_OVERVIEW: "/admin/overview",
  ADMIN_SETTINGS: "/admin/settings",
  ADMIN_ASSESSMENT_STATUS: "/admin/assessment-status",
  ADMIN_PROFILE: "/admin/profile",
  ADMIN_INDIVIDUALS: "/admin/clients/individuals",
  ADMIN_COMPANY: "/admin/clients/company",
  ADMIN_PARTERSHIPS: "/admin/clients/partnerships",
  ASMIN_INSIGHTS_AND_DUIDES: "/admin/insights-guides",

  // Accountant Routes
  ACCOUNTANT_OVERVIEW: "/accountant/overview",
  ACCOUNTANT_TAX_FILLING: "/accountant/taxfilling",
  ACCOUNTANT_CHAT_HISTORY: "/accountanta/chat-history",
  ACCOUNTANTA_INSIGHTS_GUIDES: "/accountanta/insights-guides",
  ACCOUNTANTA_SETTINGS: "/accountanta/setting",
});
export const ERROR_MESSAGE = Object.freeze({
  INVALID_EMAIL: "Invalid email",
  INVALID_PASSWORD: "Password cannot be empty",
  MISMATCHED_PASSWORD: "Passwords did not match",
});
export const USER_TYPE = Object.freeze({
  CUSTOMER: "customer",
  ADMIN: "admin",
  ACCOUNTANT: "accountant",
  BUSINESS: "business",
  SERVICE_MANAGER: "service manager",
});
